app = 'minifocs'
primary_region = 'ewr'

[build]
  image = 'miniflux/miniflux:nightly'

[env]
  MEDIA_PROXY_MODE = 'all'
  MEDIA_PROXY_RESOURCE_TYPES = 'image,audio,video'
  POLLING_PARSING_ERROR_LIMIT = '0'
  RUN_MIGRATIONS = '1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
